### ISSUE TITLE
Can I use HaplotyperCaller to find out SNP that is uniq to a population?

### ISSUE THREAD

**Issue by lychen83** [oicr-gsi/haplotypeCaller#10]
Hi,

I am new to HaplotyperCaller. I have a reference genome and genome re-sequencing data for 80 individuals from 7 populations.   Among the 7 populations, a special one (named "Mali") has re-sequencing data for 5 individuals.    
Can HaplotypeCaller can find SNP that are unique to "Mali"?    In other words, can we use HaplotypeCaller to find SNPs that can separate Mali individuals from others?

Thanks a lot.

Best,
Lingyun

**Comment by lheisler** [comment]
Hi Lingyun.
This repository houses a workflow which implements the GATK haplotype caller tool and best practices as part of our anlysis pipelines at OICR
https://gatk.broadinstitute.org/hc/en-us/articles/360035535932-Germline-short-variant-discovery-SNPs-Indels

answers to your questions can likely be found through resources available through the Broad institute or with their helpdesk
